In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [24]:
dataset = pd.read_csv('/content/Penilaiain.csv',sep=";")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
print (x)

[['Anak' 10.0 50.0]
 ['Dewasa' nan 55.0]
 ['Lansia' 55.0 nan]
 ['Lansia' 60.0 15.0]
 ['Anak' nan 60.0]
 ['Dewasa' 30.0 40.0]
 ['Dewasa' 35.0 nan]
 ['Dewasa' 28.0 45.0]
 ['Anak' nan 70.0]
 ['Lansia' 70.0 5.0]
 ['Dewasa' 32.0 nan]
 ['Dewasa' 29.0 21.0]
 ['Lansia' nan 15.0]
 ['Anak' 7.0 50.0]
 ['Anak' 8.0 45.0]]


In [26]:
print (y)

['Tidak' 'Bekerja' 'Tidak' 'Tidak' 'Tidak' 'Bekerja' 'Bekerja' 'Bekerja'
 'Tidak' 'Tidak' 'Bekerja' 'Bekerja' 'Tidak' 'Tidak' 'Tidak']


In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:2])
x[:, 1:2] = imputer.transform(x[:, 1:2])

In [28]:
print (x)

[['Anak' 10.0 50.0]
 ['Dewasa' 33.09090909090909 55.0]
 ['Lansia' 55.0 nan]
 ['Lansia' 60.0 15.0]
 ['Anak' 33.09090909090909 60.0]
 ['Dewasa' 30.0 40.0]
 ['Dewasa' 35.0 nan]
 ['Dewasa' 28.0 45.0]
 ['Anak' 33.09090909090909 70.0]
 ['Lansia' 70.0 5.0]
 ['Dewasa' 32.0 nan]
 ['Dewasa' 29.0 21.0]
 ['Lansia' 33.09090909090909 15.0]
 ['Anak' 7.0 50.0]
 ['Anak' 8.0 45.0]]


In [29]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [30]:
print (x)

[['Anak' 10.0 50.0]
 ['Dewasa' 33.09090909090909 55.0]
 ['Lansia' 55.0 39.25]
 ['Lansia' 60.0 15.0]
 ['Anak' 33.09090909090909 60.0]
 ['Dewasa' 30.0 40.0]
 ['Dewasa' 35.0 39.25]
 ['Dewasa' 28.0 45.0]
 ['Anak' 33.09090909090909 70.0]
 ['Lansia' 70.0 5.0]
 ['Dewasa' 32.0 39.25]
 ['Dewasa' 29.0 21.0]
 ['Lansia' 33.09090909090909 15.0]
 ['Anak' 7.0 50.0]
 ['Anak' 8.0 45.0]]


In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])
    ],
    remainder='passthrough'
)

x = ct.fit_transform(x)

In [32]:
print (x)

[[1.0 0.0 0.0 10.0 50.0]
 [0.0 1.0 0.0 33.09090909090909 55.0]
 [0.0 0.0 1.0 55.0 39.25]
 [0.0 0.0 1.0 60.0 15.0]
 [1.0 0.0 0.0 33.09090909090909 60.0]
 [0.0 1.0 0.0 30.0 40.0]
 [0.0 1.0 0.0 35.0 39.25]
 [0.0 1.0 0.0 28.0 45.0]
 [1.0 0.0 0.0 33.09090909090909 70.0]
 [0.0 0.0 1.0 70.0 5.0]
 [0.0 1.0 0.0 32.0 39.25]
 [0.0 1.0 0.0 29.0 21.0]
 [0.0 0.0 1.0 33.09090909090909 15.0]
 [1.0 0.0 0.0 7.0 50.0]
 [1.0 0.0 0.0 8.0 45.0]]


In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [34]:
print (y)

[1 0 1 1 1 0 0 0 1 1 0 0 1 1 1]


In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [36]:
print (x_train)

[[0.0 0.0 1.0 55.0 39.25]
 [0.0 1.0 0.0 32.0 39.25]
 [1.0 0.0 0.0 33.09090909090909 60.0]
 [0.0 1.0 0.0 33.09090909090909 55.0]
 [1.0 0.0 0.0 7.0 50.0]
 [1.0 0.0 0.0 10.0 50.0]
 [1.0 0.0 0.0 8.0 45.0]
 [0.0 0.0 1.0 70.0 5.0]
 [1.0 0.0 0.0 33.09090909090909 70.0]
 [0.0 0.0 1.0 33.09090909090909 15.0]
 [0.0 1.0 0.0 29.0 21.0]
 [0.0 1.0 0.0 30.0 40.0]]


In [37]:
print (x_test)

[[0.0 0.0 1.0 60.0 15.0]
 [0.0 1.0 0.0 28.0 45.0]
 [0.0 1.0 0.0 35.0 39.25]]


In [38]:
print (y_train)

[1 0 1 0 1 1 1 1 1 1 0 0]


In [39]:
print (y_test)

[1 0 0]


In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [42]:
print (x_train)

[[0.0 0.0 1.0 55.0 -0.0849238345541986]
 [0.0 1.0 0.0 32.0 -0.0849238345541986]
 [1.0 0.0 0.0 33.09090909090909 1.0581050737698816]
 [0.0 1.0 0.0 33.09090909090909 0.7826764211616695]
 [1.0 0.0 0.0 7.0 0.5072477685534574]
 [1.0 0.0 0.0 10.0 0.5072477685534574]
 [1.0 0.0 0.0 8.0 0.23181911594524532]
 [0.0 0.0 1.0 70.0 -1.9716101049204515]
 [1.0 0.0 0.0 33.09090909090909 1.608962378986306]
 [0.0 0.0 1.0 33.09090909090909 -1.4207527997040272]
 [0.0 1.0 0.0 29.0 -1.0902384165741728]
 [0.0 1.0 0.0 30.0 -0.04360953666296678]]


In [43]:
print (x_test)

[[0.0 0.0 1.0 60.0 -1.4207527997040272]
 [0.0 1.0 0.0 28.0 0.23181911594524532]
 [0.0 1.0 0.0 35.0 -0.0849238345541986]]
